apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: presentations
commonLabels:
 app.kubernetes.io/name: reveal-md
 app.kubernetes.io/part-of: presentations
resources:
 - namespace.yaml
 - deployment.yaml
 - service.yaml
 - git-sync-config.yaml
